// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: createincidentevent.proto

package emradiprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateIncidentEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description  string  `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Created      string  `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	Notes        *string `protobuf:"bytes,4,opt,name=notes,proto3,oneof" json:"notes,omitempty"`
	CreatedBy    *string `protobuf:"bytes,5,opt,name=createdBy,proto3,oneof" json:"createdBy,omitempty"`
	AffectedUser *string `protobuf:"bytes,6,opt,name=affectedUser,proto3,oneof" json:"affectedUser,omitempty"`
}

func (x *CreateIncidentEvent) Reset() {
	*x = CreateIncidentEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_createincidentevent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIncidentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIncidentEvent) ProtoMessage() {}

func (x *CreateIncidentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_createincidentevent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIncidentEvent.ProtoReflect.Descriptor instead.
func (*CreateIncidentEvent) Descriptor() ([]byte, []int) {
	return file_createincidentevent_proto_rawDescGZIP(), []int{0}
}

func (x *CreateIncidentEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateIncidentEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateIncidentEvent) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *CreateIncidentEvent) GetNotes() string {
	if x != nil && x.Notes != nil {
		return *x.Notes
	}
	return ""
}

func (x *CreateIncidentEvent) GetCreatedBy() string {
	if x != nil && x.CreatedBy != nil {
		return *x.CreatedBy
	}
	return ""
}

func (x *CreateIncidentEvent) GetAffectedUser() string {
	if x != nil && x.AffectedUser != nil {
		return *x.AffectedUser
	}
	return ""
}

var File_createincidentevent_proto protoreflect.FileDescriptor

var file_createincidentevent_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf1, 0x01, 0x0a, 0x13,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12,
	0x19, 0x0a, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x05, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x88, 0x01, 0x01, 0x12, 0x27, 0x0a,
	0x0c, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x0c, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x55,
	0x73, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x73,
	0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x42, 0x0f,
	0x0a, 0x0d, 0x5f, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x42,
	0x11, 0x5a, 0x0f, 0x2e, 0x2e, 0x2f, 0x65, 0x6d, 0x72, 0x61, 0x64, 0x69, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_createincidentevent_proto_rawDescOnce sync.Once
	file_createincidentevent_proto_rawDescData = file_createincidentevent_proto_rawDesc
)

func file_createincidentevent_proto_rawDescGZIP() []byte {
	file_createincidentevent_proto_rawDescOnce.Do(func() {
		file_createincidentevent_proto_rawDescData = protoimpl.X.CompressGZIP(file_createincidentevent_proto_rawDescData)
	})
	return file_createincidentevent_proto_rawDescData
}

var file_createincidentevent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_createincidentevent_proto_goTypes = []interface{}{
	(*CreateIncidentEvent)(nil), // 0: CreateIncidentEvent
}
var file_createincidentevent_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_createincidentevent_proto_init() }
func file_createincidentevent_proto_init() {
	if File_createincidentevent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_createincidentevent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIncidentEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_createincidentevent_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_createincidentevent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_createincidentevent_proto_goTypes,
		DependencyIndexes: file_createincidentevent_proto_depIdxs,
		MessageInfos:      file_createincidentevent_proto_msgTypes,
	}.Build()
	File_createincidentevent_proto = out.File
	file_createincidentevent_proto_rawDesc = nil
	file_createincidentevent_proto_goTypes = nil
	file_createincidentevent_proto_depIdxs = nil
}
