// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: emradiMessage.proto

package emradiprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmradiMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Collection Collection `protobuf:"varint,1,opt,name=collection,proto3,enum=Collection" json:"collection,omitempty"`
	Crud       Crud       `protobuf:"varint,2,opt,name=crud,proto3,enum=Crud" json:"crud,omitempty"`
	// Types that are assignable to Data:
	//
	//	*EmradiMessage_Since
	//	*EmradiMessage_Incident
	//	*EmradiMessage_User
	Data isEmradiMessage_Data `protobuf_oneof:"data"`
}

func (x *EmradiMessage) Reset() {
	*x = EmradiMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_emradiMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmradiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmradiMessage) ProtoMessage() {}

func (x *EmradiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_emradiMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmradiMessage.ProtoReflect.Descriptor instead.
func (*EmradiMessage) Descriptor() ([]byte, []int) {
	return file_emradiMessage_proto_rawDescGZIP(), []int{0}
}

func (x *EmradiMessage) GetCollection() Collection {
	if x != nil {
		return x.Collection
	}
	return Collection_incidents
}

func (x *EmradiMessage) GetCrud() Crud {
	if x != nil {
		return x.Crud
	}
	return Crud_create
}

func (m *EmradiMessage) GetData() isEmradiMessage_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *EmradiMessage) GetSince() string {
	if x, ok := x.GetData().(*EmradiMessage_Since); ok {
		return x.Since
	}
	return ""
}

func (x *EmradiMessage) GetIncident() *Incident {
	if x, ok := x.GetData().(*EmradiMessage_Incident); ok {
		return x.Incident
	}
	return nil
}

func (x *EmradiMessage) GetUser() *User {
	if x, ok := x.GetData().(*EmradiMessage_User); ok {
		return x.User
	}
	return nil
}

type isEmradiMessage_Data interface {
	isEmradiMessage_Data()
}

type EmradiMessage_Since struct {
	Since string `protobuf:"bytes,3,opt,name=since,proto3,oneof"`
}

type EmradiMessage_Incident struct {
	Incident *Incident `protobuf:"bytes,4,opt,name=incident,proto3,oneof"`
}

type EmradiMessage_User struct {
	User *User `protobuf:"bytes,5,opt,name=user,proto3,oneof"`
}

func (*EmradiMessage_Since) isEmradiMessage_Data() {}

func (*EmradiMessage_Incident) isEmradiMessage_Data() {}

func (*EmradiMessage_User) isEmradiMessage_Data() {}

var File_emradiMessage_proto protoreflect.FileDescriptor

var file_emradiMessage_proto_rawDesc = []byte{
	0x0a, 0x13, 0x65, 0x6d, 0x72, 0x61, 0x64, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x63, 0x72, 0x75, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x10, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xbd, 0x01, 0x0a, 0x0d, 0x45, 0x6d, 0x72, 0x61, 0x64, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x2b, 0x0a, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19,
	0x0a, 0x04, 0x63, 0x72, 0x75, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x05, 0x2e, 0x43,
	0x72, 0x75, 0x64, 0x52, 0x04, 0x63, 0x72, 0x75, 0x64, 0x12, 0x16, 0x0a, 0x05, 0x73, 0x69, 0x6e,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x73, 0x69, 0x6e, 0x63,
	0x65, 0x12, 0x27, 0x0a, 0x08, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x48, 0x00,
	0x52, 0x08, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x48,
	0x00, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42,
	0x11, 0x5a, 0x0f, 0x2e, 0x2e, 0x2f, 0x65, 0x6d, 0x72, 0x61, 0x64, 0x69, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_emradiMessage_proto_rawDescOnce sync.Once
	file_emradiMessage_proto_rawDescData = file_emradiMessage_proto_rawDesc
)

func file_emradiMessage_proto_rawDescGZIP() []byte {
	file_emradiMessage_proto_rawDescOnce.Do(func() {
		file_emradiMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_emradiMessage_proto_rawDescData)
	})
	return file_emradiMessage_proto_rawDescData
}

var file_emradiMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_emradiMessage_proto_goTypes = []interface{}{
	(*EmradiMessage)(nil), // 0: EmradiMessage
	(Collection)(0),       // 1: Collection
	(Crud)(0),             // 2: Crud
	(*Incident)(nil),      // 3: Incident
	(*User)(nil),          // 4: User
}
var file_emradiMessage_proto_depIdxs = []int32{
	1, // 0: EmradiMessage.collection:type_name -> Collection
	2, // 1: EmradiMessage.crud:type_name -> Crud
	3, // 2: EmradiMessage.incident:type_name -> Incident
	4, // 3: EmradiMessage.user:type_name -> User
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_emradiMessage_proto_init() }
func file_emradiMessage_proto_init() {
	if File_emradiMessage_proto != nil {
		return
	}
	file_crud_proto_init()
	file_collection_proto_init()
	file_incident_proto_init()
	file_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_emradiMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmradiMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_emradiMessage_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*EmradiMessage_Since)(nil),
		(*EmradiMessage_Incident)(nil),
		(*EmradiMessage_User)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_emradiMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_emradiMessage_proto_goTypes,
		DependencyIndexes: file_emradiMessage_proto_depIdxs,
		MessageInfos:      file_emradiMessage_proto_msgTypes,
	}.Build()
	File_emradiMessage_proto = out.File
	file_emradiMessage_proto_rawDesc = nil
	file_emradiMessage_proto_goTypes = nil
	file_emradiMessage_proto_depIdxs = nil
}
