// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: message.proto

package emradiprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmradiMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Variant:
	//
	//	*EmradiMessage_CreateIncident
	//	*EmradiMessage_CreateIncidentEvent
	//	*EmradiMessage_ReadRequest
	//	*EmradiMessage_ReadResponse
	//	*EmradiMessage_UpdateIncident
	Variant isEmradiMessage_Variant `protobuf_oneof:"variant"`
}

func (x *EmradiMessage) Reset() {
	*x = EmradiMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmradiMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmradiMessage) ProtoMessage() {}

func (x *EmradiMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmradiMessage.ProtoReflect.Descriptor instead.
func (*EmradiMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (m *EmradiMessage) GetVariant() isEmradiMessage_Variant {
	if m != nil {
		return m.Variant
	}
	return nil
}

func (x *EmradiMessage) GetCreateIncident() *CreateIncident {
	if x, ok := x.GetVariant().(*EmradiMessage_CreateIncident); ok {
		return x.CreateIncident
	}
	return nil
}

func (x *EmradiMessage) GetCreateIncidentEvent() *CreateIncidentEvent {
	if x, ok := x.GetVariant().(*EmradiMessage_CreateIncidentEvent); ok {
		return x.CreateIncidentEvent
	}
	return nil
}

func (x *EmradiMessage) GetReadRequest() *ReadRequest {
	if x, ok := x.GetVariant().(*EmradiMessage_ReadRequest); ok {
		return x.ReadRequest
	}
	return nil
}

func (x *EmradiMessage) GetReadResponse() *ReadResponse {
	if x, ok := x.GetVariant().(*EmradiMessage_ReadResponse); ok {
		return x.ReadResponse
	}
	return nil
}

func (x *EmradiMessage) GetUpdateIncident() *UpdateIncident {
	if x, ok := x.GetVariant().(*EmradiMessage_UpdateIncident); ok {
		return x.UpdateIncident
	}
	return nil
}

type isEmradiMessage_Variant interface {
	isEmradiMessage_Variant()
}

type EmradiMessage_CreateIncident struct {
	CreateIncident *CreateIncident `protobuf:"bytes,1,opt,name=createIncident,proto3,oneof"`
}

type EmradiMessage_CreateIncidentEvent struct {
	CreateIncidentEvent *CreateIncidentEvent `protobuf:"bytes,2,opt,name=createIncidentEvent,proto3,oneof"`
}

type EmradiMessage_ReadRequest struct {
	ReadRequest *ReadRequest `protobuf:"bytes,3,opt,name=readRequest,proto3,oneof"`
}

type EmradiMessage_ReadResponse struct {
	ReadResponse *ReadResponse `protobuf:"bytes,4,opt,name=readResponse,proto3,oneof"`
}

type EmradiMessage_UpdateIncident struct {
	UpdateIncident *UpdateIncident `protobuf:"bytes,5,opt,name=updateIncident,proto3,oneof"`
}

func (*EmradiMessage_CreateIncident) isEmradiMessage_Variant() {}

func (*EmradiMessage_CreateIncidentEvent) isEmradiMessage_Variant() {}

func (*EmradiMessage_ReadRequest) isEmradiMessage_Variant() {}

func (*EmradiMessage_ReadResponse) isEmradiMessage_Variant() {}

func (*EmradiMessage_UpdateIncident) isEmradiMessage_Variant() {}

var File_message_proto protoreflect.FileDescriptor

var file_message_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x14, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x69, 0x6e, 0x63,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x11, 0x72, 0x65, 0x61, 0x64, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x72, 0x65, 0x61, 0x64, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x69,
	0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc1, 0x02,
	0x0a, 0x0d, 0x45, 0x6d, 0x72, 0x61, 0x64, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x39, 0x0a, 0x0e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0e, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x48, 0x0a, 0x13, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52,
	0x13, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x0b, 0x72, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x52, 0x65, 0x61, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x72, 0x65, 0x61, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x0c, 0x72, 0x65, 0x61, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x72,
	0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0e, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x63, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e,
	0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e,
	0x74, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2e, 0x2f, 0x65, 0x6d, 0x72, 0x61, 0x64, 0x69, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData = file_message_proto_rawDesc
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_proto_rawDescData)
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_proto_goTypes = []interface{}{
	(*EmradiMessage)(nil),       // 0: EmradiMessage
	(*CreateIncident)(nil),      // 1: CreateIncident
	(*CreateIncidentEvent)(nil), // 2: CreateIncidentEvent
	(*ReadRequest)(nil),         // 3: ReadRequest
	(*ReadResponse)(nil),        // 4: ReadResponse
	(*UpdateIncident)(nil),      // 5: UpdateIncident
}
var file_message_proto_depIdxs = []int32{
	1, // 0: EmradiMessage.createIncident:type_name -> CreateIncident
	2, // 1: EmradiMessage.createIncidentEvent:type_name -> CreateIncidentEvent
	3, // 2: EmradiMessage.readRequest:type_name -> ReadRequest
	4, // 3: EmradiMessage.readResponse:type_name -> ReadResponse
	5, // 4: EmradiMessage.updateIncident:type_name -> UpdateIncident
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	file_createincident_proto_init()
	file_createincidentevent_proto_init()
	file_readrequest_proto_init()
	file_readresponse_proto_init()
	file_updateincident_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmradiMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_message_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*EmradiMessage_CreateIncident)(nil),
		(*EmradiMessage_CreateIncidentEvent)(nil),
		(*EmradiMessage_ReadRequest)(nil),
		(*EmradiMessage_ReadResponse)(nil),
		(*EmradiMessage_UpdateIncident)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_rawDesc = nil
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
