// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: updateincident.proto

package emradiprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateIncident struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Latitude     *float32 `protobuf:"fixed32,2,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude    *float32 `protobuf:"fixed32,3,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	IncidentType *string  `protobuf:"bytes,4,opt,name=incidentType,proto3,oneof" json:"incidentType,omitempty"`
	ClosedAt     *string  `protobuf:"bytes,5,opt,name=closedAt,proto3,oneof" json:"closedAt,omitempty"`
}

func (x *UpdateIncident) Reset() {
	*x = UpdateIncident{}
	if protoimpl.UnsafeEnabled {
		mi := &file_updateincident_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateIncident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIncident) ProtoMessage() {}

func (x *UpdateIncident) ProtoReflect() protoreflect.Message {
	mi := &file_updateincident_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIncident.ProtoReflect.Descriptor instead.
func (*UpdateIncident) Descriptor() ([]byte, []int) {
	return file_updateincident_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateIncident) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateIncident) GetLatitude() float32 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *UpdateIncident) GetLongitude() float32 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *UpdateIncident) GetIncidentType() string {
	if x != nil && x.IncidentType != nil {
		return *x.IncidentType
	}
	return ""
}

func (x *UpdateIncident) GetClosedAt() string {
	if x != nil && x.ClosedAt != nil {
		return *x.ClosedAt
	}
	return ""
}

var File_updateincident_proto protoreflect.FileDescriptor

var file_updateincident_proto_rawDesc = []byte{
	0x0a, 0x14, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe7, 0x01, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x49, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x08, 0x6c, 0x61, 0x74,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x08, 0x6c,
	0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x6c, 0x6f,
	0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x48, 0x01, 0x52,
	0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x88, 0x01, 0x01, 0x12, 0x27, 0x0a,
	0x0c, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x0c, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x64,
	0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x08, 0x63, 0x6c, 0x6f, 0x73,
	0x65, 0x64, 0x41, 0x74, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x6c, 0x61, 0x74, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x41, 0x74,
	0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2e, 0x2f, 0x65, 0x6d, 0x72, 0x61, 0x64, 0x69, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_updateincident_proto_rawDescOnce sync.Once
	file_updateincident_proto_rawDescData = file_updateincident_proto_rawDesc
)

func file_updateincident_proto_rawDescGZIP() []byte {
	file_updateincident_proto_rawDescOnce.Do(func() {
		file_updateincident_proto_rawDescData = protoimpl.X.CompressGZIP(file_updateincident_proto_rawDescData)
	})
	return file_updateincident_proto_rawDescData
}

var file_updateincident_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_updateincident_proto_goTypes = []interface{}{
	(*UpdateIncident)(nil), // 0: UpdateIncident
}
var file_updateincident_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_updateincident_proto_init() }
func file_updateincident_proto_init() {
	if File_updateincident_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_updateincident_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateIncident); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_updateincident_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_updateincident_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_updateincident_proto_goTypes,
		DependencyIndexes: file_updateincident_proto_depIdxs,
		MessageInfos:      file_updateincident_proto_msgTypes,
	}.Build()
	File_updateincident_proto = out.File
	file_updateincident_proto_rawDesc = nil
	file_updateincident_proto_goTypes = nil
	file_updateincident_proto_depIdxs = nil
}
